### ISSUE TITLE
Request for collaboration?

### ISSUE THREAD

**Issue by jlpedrosa** [vaerh/mikrotik-prom-exporter#23]
Ben Kochie (@superq) is a member of the observability team and I think is also a core contributor of prom, not sure if he may be up to help us in this project?

**Comment by vaerh** [comment]
Will he? I'll add it, if he doesn't mind.

**Comment by jlpedrosa** [comment]
Well at least we can tag him, I'm contributing in the unpoller (unifi exporter) and he suddenly started doing PR reviews. :rofl:

**Comment by SuperQ** [comment]
I'm not sure what the actual question is.

**Comment by jlpedrosa** [comment]
Well I'd say the question is if you are interested in participating, coding, PR reviews... etc.

**Comment by SuperQ** [comment]
Sorry, I don't have any time or interest in mikrotik metrics.
